# ======================================
# PROYECTO GLOBAL
# ======================================
sonar.projectKey=electromania
sonar.projectName=ElectroMania
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8


# ======================================
# FUENTES
# ======================================
sonar.sources=Back_Electromanía/src,electromania-frontend/src

sonar.tests=Back_Electromanía/src,electromania-frontend/src

sonar.test.inclusions=**/*.spec.ts

# ======================================
# EXCLUSIONES
# ======================================
sonar.exclusions=**/node_modules/**,**/.angular/**,**/dist/**,**/.scannerwork/**


# ======================================
# COVERAGE
# ======================================
sonar.javascript.lcov.reportPaths=Back_Electromanía/coverage/lcov.info,electromania-frontend/coverage/frontend/lcov.info

sonar.typescript.tsconfigPath=electromania-frontend/tsconfig.json,Back_Electromanía/tsconfig.json