export const INVENTORY = {
    LOW_STOCK_THRESHOLD: 5,
    CRITICAL_STOCK_THRESHOLD: 3,
    OUT_OF_STOCK_THRESHOLD: 0,
    MAX_LOW_STOCK_ITEMS: 10,
    TAX_RATE: 0.13,
    ITEMS_PER_PAGE: 10,
} as const;